### ISSUE TITLE
Can you remove the green box?Or beautify this box？

### ISSUE THREAD

**Issue by wanliyunyan** [Sensorfactdev/qr-code-scanner#3]
there is an error in the code
"Cannot read property 'getContext' of null"  in chrome 
you can like this

    const context = this.canvas && this.canvas.getContext('2d');
    if (context) {
      context.drawImage(this.videoTag, 0, 0, width, height, 0, 0, width, height);
    }`

thanks for your component!
This box does not seem to have any effect，can you remove or beautify the box

**Comment by RamonGebben** [comment]
Both points should be addressed in v1.0.10 which is on NPM already.
You can disable the aim assist by passing the prop `showAimAssist={false}`.

I hope this will serve your purpose.
